package com.example.demo.dao.pojo;

public class Countrylanguage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column countrylanguage.CountryCode
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private String countrycode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column countrylanguage.Language
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private String language;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column countrylanguage.IsOfficial
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private String isofficial;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column countrylanguage.Percentage
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private Float percentage;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column countrylanguage.CountryCode
	 * @return  the value of countrylanguage.CountryCode
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public String getCountrycode() {
		return countrycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column countrylanguage.CountryCode
	 * @param countrycode  the value for countrylanguage.CountryCode
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setCountrycode(String countrycode) {
		this.countrycode = countrycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column countrylanguage.Language
	 * @return  the value of countrylanguage.Language
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column countrylanguage.Language
	 * @param language  the value for countrylanguage.Language
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setLanguage(String language) {
		this.language = language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column countrylanguage.IsOfficial
	 * @return  the value of countrylanguage.IsOfficial
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public String getIsofficial() {
		return isofficial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column countrylanguage.IsOfficial
	 * @param isofficial  the value for countrylanguage.IsOfficial
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setIsofficial(String isofficial) {
		this.isofficial = isofficial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column countrylanguage.Percentage
	 * @return  the value of countrylanguage.Percentage
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public Float getPercentage() {
		return percentage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column countrylanguage.Percentage
	 * @param percentage  the value for countrylanguage.Percentage
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setPercentage(Float percentage) {
		this.percentage = percentage;
	}
}