package com.example.demo.dao.mapper;

import com.example.demo.dao.pojo.Country;
import java.util.List;

public interface CountryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table country
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table country
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	int insert(Country record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table country
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	Country selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table country
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	List<Country> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table country
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	int updateByPrimaryKey(Country record);
}