package com.example.demo.dao.mapper;

import com.example.demo.dao.pojo.Countrylanguage;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountrylanguageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table countrylanguage
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	int deleteByPrimaryKey(@Param("countrycode") String countrycode, @Param("language") String language);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table countrylanguage
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	int insert(Countrylanguage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table countrylanguage
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	Countrylanguage selectByPrimaryKey(@Param("countrycode") String countrycode, @Param("language") String language);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table countrylanguage
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	List<Countrylanguage> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table countrylanguage
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	int updateByPrimaryKey(Countrylanguage record);
}