package com.example.demo.dao.mapper;

import com.example.demo.dao.pojo.Upload;
import java.util.List;

public interface UploadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    int insert(Upload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    Upload selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    List<Upload> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    int updateByPrimaryKey(Upload record);
}