package com.example.demo.dao.mapper;

import com.example.demo.dao.pojo.TbProduct;
import java.util.List;

public interface TbProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	int insert(TbProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	TbProduct selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	List<TbProduct> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	int updateByPrimaryKey(TbProduct record);
}