package com.example.demo.dao.mapper;

import com.example.demo.dao.pojo.TbUer;
import java.util.List;

public interface TbUerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_uer
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_uer
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	int insert(TbUer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_uer
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	TbUer selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_uer
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	List<TbUer> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_uer
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	int updateByPrimaryKey(TbUer record);
}