package com.example.demo.dao.pojo;

public class TbProduct {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_product.id
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_product.prname
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private String prname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_product.prtype
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private String prtype;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_product.id
	 * @return  the value of tb_product.id
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_product.id
	 * @param id  the value for tb_product.id
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_product.prname
	 * @return  the value of tb_product.prname
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public String getPrname() {
		return prname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_product.prname
	 * @param prname  the value for tb_product.prname
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setPrname(String prname) {
		this.prname = prname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_product.prtype
	 * @return  the value of tb_product.prtype
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public String getPrtype() {
		return prtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_product.prtype
	 * @param prtype  the value for tb_product.prtype
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setPrtype(String prtype) {
		this.prtype = prtype;
	}
}