package com.example.demo.dao.pojo;

public class TbRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_role.id
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_role.roname
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private String roname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_role.roleid
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private Integer roleid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_role.id
	 * @return  the value of tb_role.id
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_role.id
	 * @param id  the value for tb_role.id
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_role.roname
	 * @return  the value of tb_role.roname
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public String getRoname() {
		return roname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_role.roname
	 * @param roname  the value for tb_role.roname
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setRoname(String roname) {
		this.roname = roname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_role.roleid
	 * @return  the value of tb_role.roleid
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_role.roleid
	 * @param roleid  the value for tb_role.roleid
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}
}