package com.example.demo.dao.pojo;

public class TbUer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_uer.id
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_uer.name
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_uer.productid
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private Integer productid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_uer.password
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_uer.id
	 * @return  the value of tb_uer.id
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_uer.id
	 * @param id  the value for tb_uer.id
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_uer.name
	 * @return  the value of tb_uer.name
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_uer.name
	 * @param name  the value for tb_uer.name
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_uer.productid
	 * @return  the value of tb_uer.productid
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public Integer getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_uer.productid
	 * @param productid  the value for tb_uer.productid
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_uer.password
	 * @return  the value of tb_uer.password
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_uer.password
	 * @param password  the value for tb_uer.password
	 * @mbg.generated  Sat Sep 08 15:31:37 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}