package com.example.demo.dao.pojo;

import java.util.Date;

public class Upload {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.id
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.imageurl
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    private String imageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.del_flg
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    private Integer delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.create_time
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload.id
     *
     * @return the value of upload.id
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload.id
     *
     * @param id the value for upload.id
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload.imageurl
     *
     * @return the value of upload.imageurl
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload.imageurl
     *
     * @param imageurl the value for upload.imageurl
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload.del_flg
     *
     * @return the value of upload.del_flg
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    public Integer getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload.del_flg
     *
     * @param delFlg the value for upload.del_flg
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    public void setDelFlg(Integer delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload.create_time
     *
     * @return the value of upload.create_time
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload.create_time
     *
     * @param createTime the value for upload.create_time
     *
     * @mbg.generated Sat Sep 08 15:31:37 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}